# Generated by Django 3.0.8 on 2020-07-19 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200719_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='catagory',
            field=models.CharField(choices=[('sports', 'Sports'), ('movies', 'Movies'), ('maths', 'Maths'), ('generalknowledge', 'GeneralKnowledge')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
