# Generated by Django 3.0.8 on 2020-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_questions_catagory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('-catagory',)},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.AddField(
            model_name='questions',
            name='catagory',
            field=models.CharField(choices=[('sports', 'Sports'), ('movies', 'Movies'), ('maths', 'Maths'), ('generalknowledge', 'GeneralKnowledge')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
