# Generated by Django 3.0.8 on 2020-07-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Friends')),
            ],
        ),
    ]
