# Generated by Django 3.0.8 on 2020-07-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_company_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
