# Generated by Django 3.0.8 on 2020-07-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20200721_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer1',
        ),
    ]
