# Generated by Django 3.0.8 on 2020-07-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_questions_answer1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_name',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
